language: node_js
node_js:
  - "lts/*"
env:
  - NODE_ENV=test
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - npm run migration
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm test
after_success: npm run coverage